spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blmdb
    username: postgres
    password: 123
  batch:
    initialize-schema: always
    job:
      enabled: false

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8787
